# Lösungen:

* erzeuge ein array arr1 der Form [100, 80, ... , 0] und ein array arr2 mit 100 Elementen von 0.07 bis 42 exclusiv
    - welcher Datentyp liegt jeweils vor?
    - wie kann der Datentyp explizit gesetzt werden?

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(100, -1, -20)
print(arr1, arr1.dtype)

arr2 = np.linspace(0.07, 42, num=100, endpoint=False)
print(arr2, arr2.dtype)

arr1 = np.arange(100, -1, -20, dtype=np.float32)
print(arr1, arr1.dtype)

(array([100,  80,  60,  40,  20,   0]), dtype('int64'))
(array([  0.07  ,   0.4893,   0.9086,   1.3279,   1.7472,   2.1665,
         2.5858,   3.0051,   3.4244,   3.8437,   4.263 ,   4.6823,
         5.1016,   5.5209,   5.9402,   6.3595,   6.7788,   7.1981,
         7.6174,   8.0367,   8.456 ,   8.8753,   9.2946,   9.7139,
        10.1332,  10.5525,  10.9718,  11.3911,  11.8104,  12.2297,
        12.649 ,  13.0683,  13.4876,  13.9069,  14.3262,  14.7455,
        15.1648,  15.5841,  16.0034,  16.4227,  16.842 ,  17.2613,
        17.6806,  18.0999,  18.5192,  18.9385,  19.3578,  19.7771,
        20.1964,  20.6157,  21.035 ,  21.4543,  21.8736,  22.2929,
        22.7122,  23.1315,  23.5508,  23.9701,  24.3894,  24.8087,
        25.228 ,  25.6473,  26.0666,  26.4859,  26.9052,  27.3245,
        27.7438,  28.1631,  28.5824,  29.0017,  29.421 ,  29.8403,
        30.2596,  30.6789,  31.0982,  31.5175,  31.9368,  32.3561,
        32.7754,  33.1947,  33.614 ,  34.0333,  34.4526,  34.8719,
     

* erzeuge ein leeres / mit "0" / mit "1" / mit "47.11" gefülltes array mit 10 x 20 x 30 Einträgen
    - welche Methode ist schneller und warum?
    - was gibt len(a) zurück?

In [3]:
print("empty:")
%timeit -n 100 np.empty(shape=(10, 20, 30))

print("\nzeros:")
%timeit -n 100 np.zeros(shape=(10, 20, 30))

print("\nones:")
%timeit -n 100 np.ones(shape=(10, 20, 30))

print("\n47.11:")
%timeit -n 100 np.ones(shape=(10, 20, 30)) * 47.11

empty = np.empty(shape=(10, 20, 30))
print("shape: {}, len: {}".format(empty.shape, len(empty)))

empty:
100 loops, best of 3: 820 ns per loop

zeros:
100 loops, best of 3: 2.46 µs per loop

ones:
100 loops, best of 3: 5.85 µs per loop

47.11:
100 loops, best of 3: 13 µs per loop
shape: (10, 20, 30), len: 10


* erzeuge ein 5 x 5 array mit "1" auf der Nebendiagonale (np.eye)

In [4]:
np.eye(5, 5, 1)

array([[ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.]])

* was bewirkt array.astype?

In [5]:
help(empty.astype)

Help on built-in function astype:

astype(...)
    a.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)
    
    Copy of the array, cast to a specified type.
    
    Parameters
    ----------
    dtype : str or dtype
        Typecode or data-type to which the array is cast.
    order : {'C', 'F', 'A', 'K'}, optional
        Controls the memory layout order of the result.
        'C' means C order, 'F' means Fortran order, 'A'
        means 'F' order if all the arrays are Fortran contiguous,
        'C' order otherwise, and 'K' means as close to the
        order the array elements appear in memory as possible.
        Default is 'K'.
    casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
        Controls what kind of data casting may occur. Defaults to 'unsafe'
        for backwards compatibility.
    
          * 'no' means the data types should not be cast at all.
          * 'equiv' means only byte-order changes are allowed.
          * 'safe' means o

In [6]:
data = np.random.rand(2, 10) * 4 - 2
data, data.dtype

(array([[ 0.47187383,  1.09270138, -0.03052483, -1.46184529,  0.37046604,
          1.95977672, -1.73296417,  0.65343266,  1.35358618, -1.30471387],
        [ 0.84670716, -0.13735972, -1.96045696, -1.7969439 , -0.10118188,
          1.74979303,  1.78755168, -1.67384172, -0.77462304, -1.19844754]]),
 dtype('float64'))

In [7]:
data.astype(np.int, casting='unsafe')

array([[ 0,  1,  0, -1,  0,  1, -1,  0,  1, -1],
       [ 0,  0, -1, -1,  0,  1,  1, -1,  0, -1]])

In [8]:
data.astype(np.float16, casting='safe')

TypeError: Cannot cast array from dtype('float64') to dtype('float16') according to the rule 'safe'

In [9]:
data.astype(np.float16, casting='unsafe')

array([[ 0.47192383,  1.09277344, -0.03051758, -1.46191406,  0.37036133,
         1.95996094, -1.73339844,  0.65332031,  1.35351562, -1.3046875 ],
       [ 0.84667969, -0.1373291 , -1.9609375 , -1.796875  , -0.10119629,
         1.75      ,  1.78710938, -1.67382812, -0.77441406, -1.19824219]], dtype=float16)

In [10]:
data.astype(np.float32, casting='unsafe')

array([[ 0.47187382,  1.09270144, -0.03052483, -1.46184528,  0.37046605,
         1.95977676, -1.73296416,  0.65343267,  1.3535862 , -1.30471385],
       [ 0.84670717, -0.13735972, -1.96045697, -1.7969439 , -0.10118188,
         1.74979305,  1.78755164, -1.67384171, -0.77462304, -1.19844759]], dtype=float32)

---
<p align="center">Tutorial: Einführung in NumPy von Henning Dickten und Christian Geier, PyCon.DE 2013</p>
<p align="center"><a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/deed.de"><img alt="Creative Commons Lizenzvertrag" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/88x31.png"/></a></p>

<p align="center">Dieses Werk bzw. Inhalt ist lizenziert unter einer <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/deed.de">Creative Commons Namensnennung - Nicht-kommerziell - Weitergabe unter gleichen Bedingungen 3.0 Unported Lizenz</a>.</p>

