# Lösungen:
* Erzeuge ein 8 x 8 Schachbrett mit 1 und 0

In [1]:
import numpy as np

In [2]:
chess = np.zeros(shape=(8, 8), dtype=int)
chess[1::2, ::2] = 1
chess[::2, 1::2] = 1
print(chess)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


- Wähle die farblich markierten Elemente  
![slice_7](files/files/slice_7.png "slice_7")

In [3]:
data = np.arange(1, 26).reshape(5, 5)
data

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [4]:
yellow = np.diag(data)
print("yellow:\n{}".format(yellow))

green = data[1::3]
print("\ngreen:\n{}".format(green))

blue = data[2:4, 1:3]
print("\nblue:\n{}".format(blue))

yellow:
[ 1  7 13 19 25]

green:
[[ 6  7  8  9 10]
 [21 22 23 24 25]]

blue:
[[12 13]
 [17 18]]


- Setze die Diagonalelemente (gelb) auf 42

In [5]:
data[np.diag_indices_from(data)] = 42
data

array([[42,  2,  3,  4,  5],
       [ 6, 42,  8,  9, 10],
       [11, 12, 42, 14, 15],
       [16, 17, 18, 42, 20],
       [21, 22, 23, 24, 42]])

- Wähle alle Elemente, die durch 7 teilbar UND ungerade sind  

In [6]:
arr = np.arange(100)

In [7]:
arr[(arr % 7 == 0) & (arr % 2 == 1)]

array([ 7, 21, 35, 49, 63, 77, 91])

- Wähle alle Elemente aus arr1 bei die entsprechenden Einträge in arr2 größer als 2 sind  

In [8]:
arr1 = (np.random.rand(10) * 10).astype(int)  
arr2 = (np.random.rand(10) * 10).astype(int)

print("arr1:\n  {}\narr2:\n  {}".format(arr1, arr2))

arr1:
  [9 3 0 6 7 2 5 8 2 0]
arr2:
  [0 9 5 3 0 1 4 1 6 1]


In [9]:
arr1[arr2 > 2]

array([3, 0, 6, 5, 2])

Erzeuge ein 8 x 8 int-array mit 1 auf der Diagonale, 3 auf der 2. Nebendiagonale und 9 in der unteren Dreiecksmatrix  
Tip: np.diag_indices_from, np.eye und np.tril

In [10]:
# Diagonalelemente setzen:
data = np.zeros((8, 8), dtype=int)

data[np.diag_indices_from(data)] = 1
data

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [11]:
# 2. Nebendiagonale
data[np.eye(8, 8, 2) == 1] = 3
data

array([[1, 0, 3, 0, 0, 0, 0, 0],
       [0, 1, 0, 3, 0, 0, 0, 0],
       [0, 0, 1, 0, 3, 0, 0, 0],
       [0, 0, 0, 1, 0, 3, 0, 0],
       [0, 0, 0, 0, 1, 0, 3, 0],
       [0, 0, 0, 0, 0, 1, 0, 3],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [12]:
# untere dreiecksmatrix:
data[np.tril_indices_from(data, -1)] = 9
data

array([[1, 0, 3, 0, 0, 0, 0, 0],
       [9, 1, 0, 3, 0, 0, 0, 0],
       [9, 9, 1, 0, 3, 0, 0, 0],
       [9, 9, 9, 1, 0, 3, 0, 0],
       [9, 9, 9, 9, 1, 0, 3, 0],
       [9, 9, 9, 9, 9, 1, 0, 3],
       [9, 9, 9, 9, 9, 9, 1, 0],
       [9, 9, 9, 9, 9, 9, 9, 1]])

---
<p align="center">Tutorial: Einführung in NumPy von Henning Dickten und Christian Geier, PyCon.DE 2013</p>
<p align="center"><a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/deed.de"><img alt="Creative Commons Lizenzvertrag" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/88x31.png"/></a></p>

<p align="center">Dieses Werk bzw. Inhalt ist lizenziert unter einer <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/deed.de">Creative Commons Namensnennung - Nicht-kommerziell - Weitergabe unter gleichen Bedingungen 3.0 Unported Lizenz</a>.</p>

