# 04 Grundlegende Array Operationen

In [1]:
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

## Array mit Skalaren

In [2]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [3]:
a * 2

array([0, 2, 4, 6])

In [4]:
a + 2

array([2, 3, 4, 5])

In [5]:
2 ** a

array([1, 2, 4, 8])

## Array mit Arrays

In [6]:
b = np.arange(4, 8)
b

array([4, 5, 6, 7])

In [7]:
a + b

array([ 4,  6,  8, 10])

In [8]:
a - b

array([-4, -4, -4, -4])

In [9]:
a * b  # ACHTUNG: Elementweise

array([ 0,  5, 12, 21])

In [10]:
a.dot(b)

38

## Mehrdimensional

In [11]:
a = np.ones((5, 5))
a

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [12]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [13]:
a * b

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.]])

In [14]:
a - b

array([[ 1.,  0., -1., -2., -3.],
       [ 1.,  0., -1., -2., -3.],
       [ 1.,  0., -1., -2., -3.],
       [ 1.,  0., -1., -2., -3.],
       [ 1.,  0., -1., -2., -3.]])

In [15]:
b - a

array([[-1.,  0.,  1.,  2.,  3.],
       [-1.,  0.,  1.,  2.,  3.],
       [-1.,  0.,  1.,  2.,  3.],
       [-1.,  0.,  1.,  2.,  3.],
       [-1.,  0.,  1.,  2.,  3.]])

#### auch NumPy kann keine Wunder 

In [16]:
c = np.arange(6)

In [17]:
a - c

ValueError: operands could not be broadcast together with shapes (5,5) (6,) 

## Mathematische Funktionen

In [18]:
a = np.linspace(0, 2 * np.pi, 100)
a

array([ 0.        ,  0.06346652,  0.12693304,  0.19039955,  0.25386607,
        0.31733259,  0.38079911,  0.44426563,  0.50773215,  0.57119866,
        0.63466518,  0.6981317 ,  0.76159822,  0.82506474,  0.88853126,
        0.95199777,  1.01546429,  1.07893081,  1.14239733,  1.20586385,
        1.26933037,  1.33279688,  1.3962634 ,  1.45972992,  1.52319644,
        1.58666296,  1.65012947,  1.71359599,  1.77706251,  1.84052903,
        1.90399555,  1.96746207,  2.03092858,  2.0943951 ,  2.15786162,
        2.22132814,  2.28479466,  2.34826118,  2.41172769,  2.47519421,
        2.53866073,  2.60212725,  2.66559377,  2.72906028,  2.7925268 ,
        2.85599332,  2.91945984,  2.98292636,  3.04639288,  3.10985939,
        3.17332591,  3.23679243,  3.30025895,  3.36372547,  3.42719199,
        3.4906585 ,  3.55412502,  3.61759154,  3.68105806,  3.74452458,
        3.8079911 ,  3.87145761,  3.93492413,  3.99839065,  4.06185717,
        4.12532369,  4.1887902 ,  4.25225672,  4.31572324,  4.37

In [19]:
np.sin(a)

array([  0.00000000e+00,   6.34239197e-02,   1.26592454e-01,
         1.89251244e-01,   2.51147987e-01,   3.12033446e-01,
         3.71662456e-01,   4.29794912e-01,   4.86196736e-01,
         5.40640817e-01,   5.92907929e-01,   6.42787610e-01,
         6.90079011e-01,   7.34591709e-01,   7.76146464e-01,
         8.14575952e-01,   8.49725430e-01,   8.81453363e-01,
         9.09631995e-01,   9.34147860e-01,   9.54902241e-01,
         9.71811568e-01,   9.84807753e-01,   9.93838464e-01,
         9.98867339e-01,   9.99874128e-01,   9.96854776e-01,
         9.89821442e-01,   9.78802446e-01,   9.63842159e-01,
         9.45000819e-01,   9.22354294e-01,   8.95993774e-01,
         8.66025404e-01,   8.32569855e-01,   7.95761841e-01,
         7.55749574e-01,   7.12694171e-01,   6.66769001e-01,
         6.18158986e-01,   5.67059864e-01,   5.13677392e-01,
         4.58226522e-01,   4.00930535e-01,   3.42020143e-01,
         2.81732557e-01,   2.20310533e-01,   1.58001396e-01,
         9.50560433e-02,

In [20]:
plot(a, np.sin(a));

NameError: name 'plot' is not defined

In [21]:
# cos, tan, arcos [...]

In [22]:
np.exp(a)

array([   1.        ,    1.06552381,    1.13534099,    1.20973286,
          1.28899916,    1.3734593 ,    1.46345358,    1.55934464,
          1.66151884,    1.77038788,    1.88639044,    2.00999393,
          2.14169639,    2.28202849,    2.43155569,    2.59088049,
          2.76064485,    2.94153281,    3.13427325,    3.33964277,
          3.55846889,    3.79163333,    4.04007559,    4.30479673,
          4.58686341,    4.88741218,    5.20765404,    5.54887937,
          5.91246309,    6.2998702 ,    6.71266169,    7.15250086,
          7.62115996,    8.1205274 ,    8.65261529,    9.2195676 ,
          9.8236688 ,   10.467353  ,   11.15321385,   11.88401491,
         12.66270084,   13.49240924,   14.37648329,   15.31848524,
         16.32221075,   17.39170418,   18.5312749 ,   19.74551462,
         21.03931597,   22.4178921 ,   23.88679779,   25.45195178,
         27.11966063,   28.89664411,   30.79006231,   32.80754449,
         34.95721979,   37.24775001,   39.68836449,   42.28889

In [23]:
plot(np.exp(a))

NameError: name 'plot' is not defined

## Universelle Funktionen

In [24]:
a = np.arange(600)
np.mean(a)

299.5

In [25]:
a.mean()

299.5

In [26]:
a.sum()

179700

In [27]:
%timeit a.sum()

The slowest run took 19.29 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 4.04 µs per loop


In [28]:
%timeit sum(a) #nimmt NumPys sum wegen pylab/IPython

10000 loops, best of 3: 75 µs per loop


In [29]:
b = np.arange(5 * 20).reshape(5, 20)

In [30]:
b.sum()

4950

In [31]:
b[:, 0].sum()

200

Viele dieser Funktionen können auch nur entlang einer Achse ausgeführt werden

In [32]:
b.sum(axis=0)

array([200, 205, 210, 215, 220, 225, 230, 235, 240, 245, 250, 255, 260,
       265, 270, 275, 280, 285, 290, 295])

In [33]:
b.sum(axis=1)

array([ 190,  590,  990, 1390, 1790])

In [34]:
b.mean(axis=1)

array([  9.5,  29.5,  49.5,  69.5,  89.5])

# weiter Beispiele

In [35]:
b = np.random.uniform(0, 1, 5*20).reshape(5, 20)
np.median(b)   # wieso gibts es b.median() nicht?

0.44232504716186638

In [36]:
np.median(b, axis=1)

array([ 0.42728108,  0.61118738,  0.4067801 ,  0.21196197,  0.46682613])

In [37]:
np.max(b)

0.98391772932571331

In [38]:
np.min(b)

0.002505258006401001

In [39]:
np.argmax(b)  # Index des Maximum

81

In [40]:
np.argmin(b)

25

## Transponieren

In [41]:
a = np.arange(1,26).reshape(5, 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [42]:
a.transpose()

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

In [43]:
a.T  #für faule

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

## Auf Eigenschaften von Arrays testen

In [44]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Testen ob ein min. ein Element eine Bedingung erfüllt

In [45]:
b = a > 20
b.any()  # any() ist True, wenn min. ein Element True ist

True

In [46]:
b

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True]], dtype=bool)

In [47]:
np.any(a == 0)  # noch einfacher

False

Testen ob alle Elemente eine Bedingung erfüllen

In [48]:
np.all(a > 0)

True

In [49]:
np.all(a % 2 == 0)

False

### Arrays auf Gleichheit überprüfen

In [50]:
a = np.arange(6)
b = a.copy()
c = np.arange(6).reshape(2, 3)

In [51]:
np.array_equal(a, b)  # Testet auf gleiche shape und gleichen Inhalt

True

In [52]:
np.array_equal(a, c)  

False

In [53]:
a = [1, 2]
b = [[1, 2], [1, 2]]
c = [[1, 2, 1, 2], [1, 2, 1, 2]]

Testen auf Fastgleichheit mit *np.allclose(a, b)*

In [54]:
a = [1, 2]
b = [1.00001, 2]
c = [1.0001, 2]

In [55]:
np.allclose(a, b)

True

In [56]:
np.allclose(a, c)

False

In [57]:
np.allclose(a, b, atol=1e-10)  # relative Toleranz (default ist 1e-5)

True

In [58]:
# bei nan immer False

In [59]:
np.allclose([1.0, np.nan], [1.0, np.nan])

False

# Übungen

* ziehe von einer 5x5 Matrix (Werte 0 - 25) den eigenen Mittewert ab
* normiere die Summe der Matrix auf 1 (und überprüfe dies)
* normalisiere eine Zufallsmatrix (Werte zwischen 0 und 1)
* sortiere einen Zufallsarray auf- und absteigend (sort()), kann sort() absteigend sortieren? 
* spiegel die unter Hälfte einer 10x10 Matrix (Werte von 1-100) in die obere Hälfte (np.triu(), np.tril() np.diagonal()


---
<p align="center">Tutorial: Einführung in NumPy von Henning Dickten und Christian Geier, PyCon.DE 2013</p>
<p align="center"><a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/deed.de"><img alt="Creative Commons Lizenzvertrag" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/88x31.png"/></a></p>

<p align="center">Dieses Werk bzw. Inhalt ist lizenziert unter einer <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/deed.de">Creative Commons Namensnennung - Nicht-kommerziell - Weitergabe unter gleichen Bedingungen 3.0 Unported Lizenz</a>.</p>

